### ISSUE TITLE
"Access to path denied" error

### ISSUE THREAD

**Issue by SchmittDotNet** [aspnet/RoslynCodeDomProvider#10]
Using Microsoft.CodeDom.Providers.DotNetCompilerPlatform v1.0.5 in a Web API application targeting .NET 4.6.1 causes errors on rebuilding after the solution has been run in debugger:

Unable to copy file "C:\Code\Sdn\ODataService\packages\Microsoft.Net.Compilers.2.2.0\tools\System.Reflection.Metadata.dll" to "bin\roslyn\System.Reflection.Metadata.dll". Access to the path 'bin\roslyn\System.Reflection.Metadata.dll' is denied.

The error happens around 17 times for each file to copy. There are no errors when rolling back to v1.0.4.

**Comment by Jinhuafei** [comment]
Codedom provider leverages Roslyn compilation service(VBCSCompiler.exe) to compile the dynamically generated code. In 1.0.5 release, we increased the idle time of VBCSCompiler.exe from 10 sec to 10 mins to improve the startup performance in VS environment. Since those files are being used by VBCSCompiler.exe process, the copy fails. To workaround the issue, you can kill VBCSCompiler.exe process before recompiling the solution. 
Thanks for reporting the issue, we will work on the fix.

**Comment by Jinhuafei** [comment]
The fix is included in 1.0.6 release.

**Comment by mealbarracin10** [comment]
this bug is present in version 1.0.8

**Comment by xt0rted** [comment]
I was getting this error when building on azure with kudu on version 1.0.7 and 1.0.8, and intermittently on appveyor with version 1.0.8.

After further investigation it turned out that `Microsoft.Net.Compilers` and `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` were installed to all of my projects. Once I removed `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` from all but the website project the build started succeeding again. I'm not sure if this is the same issue others are experiencing, but it's worth double checking your packages to make sure only the ones you need are installed for each project.

**Comment by Jinhuafei** [comment]
@mealbarracin10 @xt0rted Is it possible for you to share your build log?

**Comment by xt0rted** [comment]
@Jinhuafei Here's two different AppVeyor build logs from the same project when this was happening intermittently https://gist.github.com/xt0rted/f741eb9410b2ee7d756d8bc47341987b

**Comment by Jinhuafei** [comment]
Thanks @xt0rted . Are Domain.csproj and EquineExchange.HelloSign.csproj web projects? DotNetCompilerPlatform is supposed to install on web project only.

**Comment by xt0rted** [comment]
No they aren't. I'm not sure why those had the package added, but I think it was from a bad update where all projects were selected instead of just the web project. After asking around I had a few people confirm that this package was only for web projects and once I removed it from the others the build started passing. Locally they always did, it was just on AppVeyor where it was intermittent and on Kudu where it was every build.

**Comment by DarinMacRae** [comment]
There should be some kind of error (warning is fine) if this package inadvertently gets added to a non-web project. This has cost many of us time and frustration. Thank you to all that raise the issue up to make it easier to find and fix.
