### ISSUE TITLE
Roslyn folder is not copied into the directory of application

### ISSUE THREAD

**Issue by MartinEgli** [aspnet/RoslynCodeDomProvider#115]
I use the nuget in a library. The Roslyn folder is not copied into the directory of my WPF application.

**Comment by rolivares** [comment]
same thing here in MVC5 application on using deploy to publish. 
multiple tips like reinstall or add custom publication files on AfterBuild does not works ... 

any idea?

**Comment by StephenMolloy** [comment]
For the WPF app, the package has traditionally been focused on web apps and sometimes gets things wrong with non-web apps. This might be alleviated with #131.

Also, in either case, this could be an $(OutDir) issue which has been more common with CI/msbuild machines vs VS environments. This is hopefully fixed by #130.

Please reopen if this is still an issue with the latest preview.
