### ISSUE TITLE
System.CodeDom.Compiler.CompilerInfo.CreateProvider fails after upgrading Microsoft.CodeDom.Providers.DotNetCompilerPlatform from v1.x to v2.x or later

### ISSUE THREAD

**Issue by k-eb** [aspnet/RoslynCodeDomProvider#117]
In our project we use the Roslyn compiler via your Nuget package to **dynamically compile C# code** at runtime using the System.CodeDom API from .NET Framework's System.dll.
The initiating code looks like this:

```c#
CompilerInfo compilerInfo = CodeDomProvider.GetCompilerInfo("C#");
CodeDomProvider provider = compilerInfo.CreateProvider(new Dictionary<string, string> { { "CompilerVersion", "v4.0" } });
```

After having ugpraded Microsoft.CodeDom.Providers.DotNetCompilerPlatform **from v1.0.7 to v2 and later**, `compilerInfo.CreateProvider` throws an exception saying **"This CodeDomProvider type does not have a constructor that takes providerOptions - "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider"**

### Env

- .NET Framework v4.8 (but also reproducible in earlier versions)
- Microsoft.CodeDom.Providers.DotNetCompilerPlatform version 2.0.0 (but also reproducible with later versions up to v3.6)
- Windows 10

### Steps to reproduce
1. Create a .NET Framework console app (e.g. targeting 4.8)
1. Add the code snippet to its Main method:
   ```c#
     CompilerInfo compilerInfo = CodeDomProvider.GetCompilerInfo("C#");
     CodeDomProvider provider = compilerInfo.CreateProvider(new Dictionary<string, string> { { "CompilerVersion", "v4.0" } });
   ```
1. Add a nuget reference to Microsoft.CodeDom.Providers.DotNetCompilerPlatform using **at least version 2.0**
1. Run the app: You will get an exception stating **"This CodeDomProvider type does not have a constructor that takes providerOptions - "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider"**
1. Remove the reference to Microsoft.CodeDom.Providers.DotNetCompilerPlatform and its dependency Microsoft.Net.Compilers
1. Readd the nuget reference to Microsoft.CodeDom.Providers.DotNetCompilerPlatform **but now using version 1.0.8**
1. Run the app: Now the provider is created without exception

**Comment by cmlr72** [comment]
Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider needs a constructor that takes an IDictionary<string, string>.

See [CompilerInfo.CreateProvider source](https://referencesource.microsoft.com/system/R/82a2a7298c77e613.html)

**Comment by StephenMolloy** [comment]
I was confused by this at first, but I think you'll find that this does indeed repro with the v1 package as well. In all likelihood, you don't have the providers from this package wired up in config. I didn't investigate why that didn't happen for me since v1.X is very long ago and won't be updated... but when I installed those old packages for a repro, they didn't update my config for whatever reason. (My best off-the-top-of-my-head-guess... the package was developed originally for web projects. If your app isn't using web.config, then your config probably didn't get updated automatically.)

Not that that resolves your issue. But "this never worked" is the information I've got after a first glance.
