### ISSUE TITLE
C# 9 support

### ISSUE THREAD

**Issue by Bonuspunkt** [aspnet/RoslynCodeDomProvider#118]
are there any plans for a update?

**Comment by StephenMolloy** [comment]
There is no refresh of this package on the immediate horizon. Additionally, the full 4.8 .Net Framework only officially supports C# 7.3. I do anticipate there will be periodic refreshes of the `Microsoft.Net.Compilers` package contained within this project when there is a compelling reason to do so, but even then, using the package 'as is' will only result in C# 7.3 for full framework projects.

Of course that does not mean that you can't get C# 8 or higher to work, even if it's not supported. But you do so at your own risk.

You should see that the compiler that gets registered in your config file when you install this package specifies "/langversion:default" in the `compilerOptions` attribute. Simply update that do specify a higher C# version number. If you need to update the `Microsoft.Net.Compilers` package, you will need to download the new version manually and place the files somewhere visible to your project. Then use the [RoslynToolPath](https://github.com/aspnet/RoslynCodeDomProvider#build-time-options) setting to point to those compiler bits when building your project.

**Comment by Bonuspunkt** [comment]
since this took me way too long - some guidance:

- install `Microsoft.Net.Compilers.Toolset` package (`Microsoft.Net.Compilers` is deprecated)
- add following snippet to your `csproj` (path needs adaption to your project structure / package version)
```xml
  <PropertyGroup>
    <RoslynToolPath>$([System.IO.Path]::GetFullPath('$(ProjectDir)\..\packages\Microsoft.Net.Compilers.Toolset.3.8.0\tasks\net472'))</RoslynToolPath>
  </PropertyGroup>
```

**Comment by StephenMolloy** [comment]
Please note that if you add the `Microsoft.Net.Compilers.Toolset` package directly to your project, there might be some affect in the Visual Studio design time experience. I don't recall the exact details because I was not the owner of this package when we made the change to ship the roslyn tools directly inside this package... but I believe the gist is that VS uses its own roslyn tools at design time and when a project directly references a different version of the roslyn tools, the mismatched expectations can cause some funkiness somehow. Again, the details are not well known to me, but it was intentional to stop making the package reference and to instead contain the binaries right inside this package.

Its probably not a big deal. But if you run into some odd design time behavior, or mismatched behavior from "run time" after making this change, this might be a reason why. To remedy this and emulate the non-VS-interfering approach that this package takes, you could indirectly download the new toolset package outside of your project without a nuget reference in your project and then point the `RoslynToolPath` property wherever you stashed those bits.

**Comment by fredericDelaporte** [comment]
I only have the DotNetCompilerPlatform package in my .Net 4.8 project and I already have that mismatch. On dynamically compiled .cs files, the VS IDE suggests me latest syntax changes, whatever the value of langversion in the csproj or the web.config. And without fiddling with the `/langversion:default` setting in web.config codedom registration, it was actually working up to c#8, while the statically compiled .cs were still limited to c#7.3 when letting the csproj in its default configuration. (For statically compiled files, the IDE is not suggesting newer syntax, so this was not much of an issue. Still for consistency, this has led me to enable c#8 in the csproj.)

But now the IDE has started suggesting c#9 syntax in dynamically compiled files, and happily does the changes. But then my site crashes at runtime. I can enable c#9 in the csproj, but it only works for statically compiled files. Enabling it on the codedom node in web.config does crash the site.

So here I am, looking for whether c#9 is going to be supported by DotNetCompilerPlatform or not. For me it would then just be a matter of upgrading it to get this mismatch fixed, since most IDE suggestions are compile-time only features, able to run whatever the target framework.

It seems it is not going to be supported. Should I open an issue for the mismatch in code suggestion for dynamically compiled files?

**Comment by StephenMolloy** [comment]
@fredericDelaporte, you mention a csproj file. Is this a web application, or some other type of C# project?

**Comment by fredericDelaporte** [comment]
It is a web application csproj, old format of csproj (not sdk style).

**Comment by khellang** [comment]
It would indeed be awesome with a new release with support for C# 9. Right now we're running our entire .NET Framework project on C# 8 (with our own polyfilled types) with no issues. We've been holding back the `LangVersion` switch on the project while waiting for an updated CodeDom provider for the aspx files for the reasons @fredericDelaporte mentions 😊
