### ISSUE TITLE
Microsoft.CodeDom.Providers.DotNetCompilerPlatform version 3.6.0 contains a vulnerable library System.Net.Http

### ISSUE THREAD

**Issue by christiansita** [aspnet/RoslynCodeDomProvider#123]
According to https://github.com/aspnet/Announcements/issues/239, there is an **Elevation of Privilege** vulnerability with **System.Net.Http** library version **4.1.1**. But, the latest version of **Microsoft.CodeDom.Providers.DotNetCompilerPlatform** library contains the vulnerable System.Net.Http at this location **tools/Roslyn46/System.Net.Http**. Is it possible to have System.Net.Http upgraded to latest fixed version such as **4.3.4**?

**Comment by TobiasWenzel** [comment]
Same issue here. WhiteSource reports vulnerabilites in Pull requests Microsoft.CodeDom.Providers.DotNetCompilerPlatform 3.6.0 and there is no later version of it.

Probably the same issue is #84. Unfortunately it was already closed and users are left behind with confusion.
The only remark from Microsoft is from 2019: https://github.com/aspnet/RoslynCodeDomProvider/issues/84#issuecomment-552037345
But I don't know if this still applies to v3.6.0 and if we can just say that System.Net.Http is not used...

**Comment by StephenMolloy** [comment]
Yes, this is the same as #84. The reported vulnerability is in roslyn binaries, not this project. But we do include raw binary drops from the roslyn tools package within this package. If your 'targetFramework' is 4.7.2 or newer, then we don't include the flagged version of roslyn in your application output. It will continue to exist in our own package directory though for projects that target frameworks older than 4.7.2.

Due to compatibility concerns, there really isn't much we can do about this. We have to include the raw binary toolset for the roslyn versions we support to avoid conflict with tools that use a direct nuget-dependency. And we can't necessarily update the binaries underneath the noses of apps that are not aware they are being updated or don't want to be updated.

What we can do is stop supporting old platforms. .Net Framework 4.6.2 is still supported... but that doesn't mean future releases of this package have to support it. Old versions of this package will still work on 4.6.2 - and will thus continue to get flagged for the packaged vulnerability.

The 3.X releases of this package will continue to support the oldest current framework - and will as a result continue to be flagged. The upcoming 4.X release will move to stop supporting older versions though and will be able to stop including old flagged binaries.
