### ISSUE TITLE
Allow overriding version through MSBuild property

### ISSUE THREAD

**Issue by khellang** [aspnet/RoslynCodeDomProvider#143]
Hello @StephenMolloy! 👋

How's the 3.11 version coming along?

Would it be possible to include an easy way to set the desired compiler version through an MSBuild property?

By conditionally setting the following properties, only if they haven't already been set, you could allow users that want to wander "off the beaten track" to override the compiler version in order to use newer compiler/language features:

https://github.com/aspnet/RoslynCodeDomProvider/blob/960f11f63bc33f99c6a6bfd903b1a1daccb2e1d9/tools/RoslynCodeProvider.settings.targets#L22-L25

**Comment by StephenMolloy** [comment]
I don't think we could commit to officially supporting this configuration. However, if you really want to "bring your own" roslyn compiler, you always have the option to use the [`RoslynToolPath`](https://github.com/aspnet/RoslynCodeDomProvider#build-time-options) property to point this provider at a specific roslyn toolset. This does require you to have downloaded the specific toolset already, rather than simply supplying a version number. But it is otherwise a similar concept.
