### ISSUE TITLE
updating package from 3.6 to 4.1 deletes roslyn folder from Bin and references in web.config

### ISSUE THREAD

**Issue by mnoreen** [aspnet/RoslynCodeDomProvider#149]
We have a C# website (not "project", a website) based on .NET Framework 4.8 with a package reference to version 3.6.  In web.config, there was a system.codedom block like:

`      <compiler extension=".cs" language="c#;cs;csharp" warningLevel="4" compilerOptions="/langversion:7.3 /nowarn:1659;1699;1701;612;618" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
`

After using nuget to update the package to 4.1... the rosyln folder in the web's Bin directory was deleted as well as the system.codedom section of the web.config.  And... consequently any code that did something like string interpolation

`
txtHello.Text = $"Hello world {DateTime.Now}";
`
Now produces an error: 

CS1056: Unexpected character '$'

**Comment by looc** [comment]
I have the same problem, can´t find any way around it.

**Comment by aerichmond** [comment]
I ran into the same problem with a site I maintain. Hoping there is a solution.

**Comment by StephenMolloy** [comment]
I'm afraid I didn't make this very clear in the Readme of this site or the nuget feed. I will try to call this out more obviously.

The 4.X major version update of this package moves to a 100% msbuild/targets method of integration with projects. This was necessary because of the direction NuGet has moved over the years - most relevantly in this case, dropping support for `install.ps1` scripts in packages. This new msbuild/targets approach should be more reliable for the vast majority of projects that use this package.

`Web Sites` are old and project-less, and as such they have minimal support in msbuild. The new integration approach taken in 4.X does not work for websites. I did not anticipate there would be many active 'Web Site's out there that would actively update to the newest version of the Roslyn CodeDom provider. The 3.11 release will still work with 'Web Site's as previous releases did.

However, seeing that there are still websites staying up-to-date with this package, I'm thinking of releasing a new companion package to this that will restore the `install.ps1` approach for websites only. Could you give the [Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites/4.1.0-preview1) preview package a try and see if it resolves the issue for you?

**Comment by looc** [comment]
Hi
Im afraid we are still using web-sites and have some old large sites that is not that easy to convert.

Installing [Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites] on a 3.11 will give an error, see below
First upgrading to 4.1 and then installing ...Websites will give the same error.

----Error output, personal data removed----
Attempting to gather dependency information for package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1' with respect to project '___.__.___', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 23 ms
Attempting to resolve dependencies for package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1'
Resolved actions to install package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1'
Executing script file 'C:\Users\_______________________________________________\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.3.11.0\tools\uninstall.ps1'...
Removed package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.3.11.0' from 'packages.config'
Successfully uninstalled 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.3.11.0' from ___.__.___
Adding package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0' to folder 'C:\Users\_______________________________________________\packages'
Added package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0' to folder 'C:\Users\_______________________________________________\packages'
Added package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0' to 'packages.config'
Successfully installed 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform 4.1.0' to ___.__.___
Adding package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1' to folder 'C:\Users\_______________________________________________\packages'
Added package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1' to folder 'C:\Users\_______________________________________________\packages'
Added package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1' to 'packages.config'
Executing script file 'C:\Users\_______________________________________________\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1\tools\install.ps1'...
Get-Item : Cannot find path 'C:\Users\_______________________________________________
\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0-preview1' because it does not exist.
At C:\Users\_______________________________________________\packages\Microsoft.CodeDo
m.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1\tools\install.ps1:39 char:6
+ if ((Get-Item $compilerPackageDirectory) -isnot [System.IO.DirectoryI ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\____....4.1.0-preview1:String) [Get-Item], ItemNotFoundExcep 
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
 
Install failed. Rolling back...
Executing script file 'C:\Users\_______________________________________________\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1\tools\uninstall.ps1'...
Removed package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1 : Microsoft.CodeDom.Providers.DotNetCompilerPlatform [4.1.0, 4.1.0]' from 'packages.config'
Removed package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0' from 'packages.config'
Package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.3.11.0' already exists in folder 'C:\Users\_______________________________________________\packages'
Added package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.3.11.0' to 'packages.config'
Executing script file 'C:\Users\_______________________________________________\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.3.11.0\tools\install.ps1'...
Restored system.codedom compiler for extension '.cs'.
Restored system.codedom compiler for extension '.vb'.
Removing package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1 : Microsoft.CodeDom.Providers.DotNetCompilerPlatform [4.1.0, 4.1.0]' from folder 'C:\Users\_______________________________________________\packages'
Removed package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites.4.1.0-preview1 : Microsoft.CodeDom.Providers.DotNetCompilerPlatform [4.1.0, 4.1.0]' from folder 'C:\Users\_______________________________________________\packages'
Removing package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0' from folder 'C:\Users\_______________________________________________\packages'
Removed package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0' from folder 'C:\Users\_______________________________________________\packages'
Executing nuget actions took 15,98 sec
System.Management.Automation.RuntimeException: The install.ps1 cannot find the installation location of package Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0-preview1, or the pakcage is not installed correctly. ---> System.Management.Automation.RuntimeException: The install.ps1 cannot find the installation location of package Microsoft.CodeDom.Providers.DotNetCompilerPlatform.4.1.0-preview1, or the pakcage is not installed correctly.
..... 
========== Finished ==========

**Comment by mnoreen** [comment]
@StephenMolloy  Thank you for your reply. We have a large ASP.NET website that is, quite frankly, rock solid and is actively maintained and added to with new features.  We have kept it up as up to date as possible (up to Framework 4.8).  There is no easy path to REWRITE 15 years worth of content, functionality etc.   And really, it's a rewrite for the sake of a rewrite, which is frustrating, but we understand it's being forced on us whether we like it or not.

In the meantime, we would like to continue to stay as updated as possible.  It is unfortunate that we are limited to C# 7.3, but that is still worth bringing in to the solution.  So if you can keep this package viable for "legacy" yet proven codebases, that would be greatly appreciated.

**Comment by looc** [comment]
Hi
Did  a test-upgrade from 3.6 and first time i got compiler error -532462766 . I first installed normal 4.1.0 and then the .websites package and when i try to a debug i get this error in the web browser. No error in VS

Restored and tried again , just installing "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites - 4.1.0-preview2" and it worked 

Restored and tried again , and installed just like the first time and that also worked, hmm , don´t know what i did different the first time.

The conclusion is that the .websites addon works for upgrading to 4.1.0, great job

**Comment by KKire** [comment]
If I start the project clean (VS closed, 'bin' and 'obj' and 'packages' folders deleted) And start IIS Express. I get error Could not find file '(...)\bin\roslyn\csc.exe'.

After this I can 100% fix the error all the time by doing Clean and then Rebuild in Visual Studio, which creates 'roslyn' folder and all files in it and the project runs fine.

Same issue in v3.11 but not in v3.6

**Comment by StephenMolloy** [comment]
The [Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.WebSites/4.1.0) package is released.

**Comment by aerichmond** [comment]
@StephenMolloy - Just wanted to say thank you.  The preview has been working flawlessly on a production environment for a little while now
