### ISSUE TITLE
Compiliation never completes when code analysis is turned on

### ISSUE THREAD

**Issue by OMortensen** [aspnet/RoslynCodeDomProvider#150]
see: https://developercommunity.visualstudio.com/t/Website-project-does-not-compile/10270700

The short end is if I have a web site project (as opposed to a web application project) and I attempt to compile with code analysis turned on, the compile never completes (I've left it running for as long as 10 days). If I turn code analysis off, it completes.

**Comment by StephenMolloy** [comment]
Honestly, I don't know that this is related to the DotNetCompilerPlatform package. From the description in the original feedback ticket, it looks like your development environment got corrupted or restored in an unexpected way. Bill Hiebert mentions that VS uses the ".refresh" files in the bin directory to ensure those "dependencies" are kept up to date when building. For this package, those ".refresh" files simply point into the package directory. This is all just a duct-tape tactic to bring some project-like functionality to a basic directory which is not a project. But the contents of that ".refresh" file should always point into the packages directory for your solution... and for some reason that connection was broken.

The original feedback ticket progresses from there, trying this or that and running into various new dead-ends. Ultimately, it looks like you solved your problem by recreating the solution entirely. But I didn't see anything that points to this package being the source of the problem.

The dump that was shared had a thread that was inside the ASP.Net compilation section that was waiting for Assembly.Load() to return from loading one of the assemblies that is created as part of the site compilation. Pass or fail. Just return. I can't say why Assembly.Load() was not returning. But I can't imagine why that would be the fault of this package.

I am not able to reproduce the error myself. If you happen to have a small, consistent repro of the issue then I think that would be helpful for the VS team to disect what is going on - as I think there's an environmental or dependent-process component to the failure here that isn't captured in the VS dump.

**Comment by OMortensen** [comment]
That’s too bad. We’ve been struggling with this compile issue for 10 years or more (every developer who starts work on the project has the same issue). It’s one of the reasons (though not even a big one) that the company I work for is moving to Worpress (I HATE Worpress with a passion, but whatever). I’m sorry to be leaving the asp-dot-net environment.

Regards,
Owen Mortensen

**Comment by StephenMolloy** [comment]
I can understand how frustrating it feels when it doesn't feel like you get the help you need. I would point out that _this_ particular package is not 10 years old. I think the original feedback ticket that involves the VS/WebTools team is the place to continue this investigation because it should include folks from VS and ASP.Net (which, full disclosure, is still me). But I don't see evidence that _this_ specific package is the cause of the issue here.

It sounds like your team has been hitting this problem frequently for a very long time. Is it possible to provide or describe a minimal repro? Is this an issue that is predicatable, or does it only pop up from time to time? I didn't see an obvious culprit in the dump provided via the original feedback issue. But that was just the VSHost process. Compilation of an ASP.Net website is quite a bit more environment-dependent beyond what we can see in a single-process dump. Which is why it would be useful to dig deeper into creating or describing repro conditions.

I didn't mean to shut down all discussion on your issue - just redirect it back to the VS forum. It will likely die here otherwise. ☹️  I would encourage you to restart the discussion on the original feedback ticket. There are more and more appropriate eyeballs there.

**Comment by OMortensen** [comment]
We have (had) a large asp.net web site project (as opposed to a web application project) that started way back when asp.net was fairly new (actually started as a classic asp – vbsript – project that was then converted to vb.net/asp.net then to a mixture of Vb.net and c# then to just c#/asp.net). There was an attempt about 5 years ago to convert to a web application project, but that was cancelled in favor of doing new development (sigh).

At any rate, the project has about 120 directories in its root and 41 directories in app_code.

One thing that used to work, when a new developer started working on the project, was to NOT configure the virtual directories (the ones with thousands of images in them) until after the developer had gotten the project to compile at least once. Then we could configure them (with limited images) and they could then proceed with development. Not sure if that would still work, since development on that project has halted. I’ve had to shut down IIS on my development machine in favor of nginx and Wordpress (ugh).

Owen
