### ISSUE TITLE
When upgrading/installing the package in visualstudio, the language version is reset to default.

### ISSUE THREAD

**Issue by MarcelDevG** [aspnet/RoslynCodeDomProvider#28]
[See Issue on developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/content/problem/99154/error-bc36716-visual-basic-120-does-not-support-in.html?childToView=164260#comment-164260)

I can understand the reason for vs2015, but can it leave the setting when in vs2017 be preserved?

Thanks

**Comment by Jinhuafei** [comment]
When updating the CodeDomProvider, we may consider to preserve the CodeDom setting in the web.config.

**Comment by StephenMolloy** [comment]
Borrowing a feature from Microsoft.Configuration.ConfigurationBuilders... this should be "fixed" by #104. The fix is to temporarily store config information when this package uninstalls, so it can be reused when reinstalling. However, since 2.0.1 didn't have this ability, your initial upgrade to 3.5 will still see this issue. Re-installing or upgrading after your first 3.5 install should not hit this anymore though.
