### ISSUE TITLE
Roslyn compiler is copied to root directory

### ISSUE THREAD

**Issue by wpsmmb** [aspnet/RoslynCodeDomProvider#41]
**Version Used**: 
1.0.6, 1.0.7, 1.0.8

**Steps to Reproduce**:
Use the compiler in a non ASP.NET project to compile dynamic assemblies as follow:
```
string classSource = "// some source"; 

CompilerParameters options = new CompilerParameters {
	GenerateExecutable = false,
	GenerateInMemory = true,
	IncludeDebugInformation = true,
	CompilerOptions = "/define:DEBUG"
};

CodeDomProvider provider = new CSharpCodeProvider();
CompilerResults result = provider.CompileAssemblyFromSource(options, classSource);
```

**Expected Behavior**:
Roslyn files will be located in subfolder of the project.

**Actual Behavior**:
The compiler is copied to 'C:\bin\roslyn' or if the solution is located on drive D the files are copied to 'D:\bin\roslyn'.

**Comment by wpsmmb** [comment]
I think https://github.com/aspnet/RoslynCodeDomProvider/pull/32 will close this issue.

**Comment by bzier** [comment]
@Jinhuafei Do you have any estimate for when the next version (>=1.0.9) will be available on the official/stable channel? I was experiencing this problem on our TeamCity build agent with 1.0.8 and attempted 1.0.9 from your comment [here](https://github.com/aspnet/RoslynCodeDomProvider/issues/38#issuecomment-372845225), which seems to have fixed it. Just curious when that version will be released. Thanks.

FYI, our project is a ServiceStack web project. I was a little surprised that the `$(WebProjectOutputDir)` is not specified for that. However, I was seeing the roslyn stuff get copied to the root of the drive (as mentioned in this issue) and the build failing during OctoPack due to the missing files in the proper output directory.

**Comment by Jinhuafei** [comment]
@bzier I'm trying to get another fix into the next release, after finish the testing we will publish it. In the meanwhile, can you give it a try with the private build which you can get from this [myget feed](https://www.myget.org/F/roslyncodedomprovider/api/v3/index.json)?

**Comment by bzier** [comment]
@Jinhuafei Yes, I pulled the 1.0.9 package from the MyGet feed and that is working for us. Thank you.

**Comment by Jinhuafei** [comment]
2.0.0-preview is released. After upgrading Microsoft.CodeDom.Providers.DotNetCompilerPlatform nupkg, please remember to uninstall Microsoft.Net.Compilers nupkg in your project.

**Comment by bzier** [comment]
Thanks for the update @Jinhuafei
