### ISSUE TITLE
CodeDomProvider compile in memory?

### ISSUE THREAD

**Issue by niemyjski** [aspnet/RoslynCodeDomProvider#5]
Is there any specific reasons that the the code dom providers shell the compiler instead of using roslyn to compile the assembly in process?

**Comment by Jinhuafei** [comment]
Copied from the other thread.

The problem was controlling the memory allocated by the compiler in certain cases. There are some generated code patterns that the aspx code generator generates that cause the Roslyn compiler to either stackoverflow or run out of memory parsing. The only way to fix that was to run then compiler out of process (since there were no changes being made to code gen)

We tried both, and out-proc compilation model works better. Besides what David mentioned, we also saw working set increment in w3wp process when using in-proc compilation.
