### ISSUE TITLE
Update the Microsoft.Net.Compilers version to 2.10.0

### ISSUE THREAD

**Issue by pantosha** [aspnet/RoslynCodeDomProvider#67]
The version 2.10.0 of the Roslyn compilers was released. It makes sense to update RoslynCodeDomProvider too.

See:
https://www.nuget.org/packages/Microsoft.Net.Compilers/
https://github.com/dotnet/roslyn/issues?q=is%3Aissue+milestone%3A15.9+label%3AArea-Compilers+is%3Aclosed

**Comment by maxtoroq** [comment]
Is anyone listening?

**Comment by gregpakes** [comment]
Doesn't look like anything has happened on this repo in over a year.

**Comment by StephenMolloy** [comment]
Done in #67.

**Comment by UweKeim** [comment]
For anyone coming here with this error message:

> ASPNETCOMPILER : error CS1617: Invalid option '7.3' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6.

I had to delete an old "bin\Roslyn" folder in my Web Application to make this work, as it seems that the newer Microsoft.Net.Compilers NuGet package (3.6.0 in my case) does not bring a its own "Rosyln" folder anymore, and if present, that old "Roslyn" folder took precedence during compilation.

See also [this related Stack Overflow question](https://stackoverflow.com/q/32380064/107625).

**Comment by StephenMolloy** [comment]
@UweKeim, This definitely shouldn't be the case, and I'd like to help figure out what is happening in your situation. This package has included packaged versions of the Roslyn binaries since v2.0 and should still be copying the appropriate new binaries to the 'bin\Roslyn' folder when the project is built.

The way this works is using a .targets file when compiling your project. By referencing this package, your project should also include the "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.targets" file. This file defines a target named "CopyRoslynCompilerFilesToOutputDirectory" which will kill the Roslyn compiler server to make sure the deployed binaries are not in use, then copy the correct binaries to "bin\Roslyn" if the files are not the same as the ones already there.  If you're not using and MSBuild environment, then you might have to manually copy these files... but it does not sound like that is the case for you. Rather it sounds like the .targets file partly did its job and copied the files over, but only _after_ you deleted the old folder?

Perhaps there was a strange ACL issue with your old folder that prevented the build process from overwriting the old binaries with the new? Is this issue easily reproducible? Are you able to share repro steps or a simple repro project that produces this issue?

**Comment by UweKeim** [comment]
Thanks, @StephenMolloy I've took a look again, and now there _is_ a "Roslyn" folder again. I think I'm going crazy. Last time there wasn't, I swear!

Could it be related to the fact that I not only do my NuGet updates inside Visual Studio but also sometimes from command line via the NuGet client?

I've [read somewhere](https://stackoverflow.com/q/15474452/107625) that when doing from a NuGet update from command line, that some scripts are not executed as compared to when done inside VS. So maybe I did a NuGet update from command line, which in turn did not execute the script to modify my CSPROJ file to include that new "CopyRoslynCompilerFilesToOutputDirectory"  target?

Does this sound sane or am I completely on the wrong track?

**Comment by StephenMolloy** [comment]
The fact that you had "/langversion:7.3" in your config says that the install scripts for the new package version ran correctly. The copying of roslyn files to the 'bin\Roslyn' directory though is not done by nuget scripts. Instead, it is done at compile time for the project via that *.targets file I mentioned. It does it this way because people don't want to check the 'bin' folder and all those supporting roslyn binaries into their source control. But when nuget "restores" packages, it doesn't run any scripts. Nuget only runs scripts when "installing." So we make sure to fix up the 'bin\Roslyn' folder at compile time.

Also, the fact that a correct 'bin\Roslyn' binary drop is happening after you deleted the old folder suggests that the *.targets copying mechanism is working roughly as expected. Why it didn't work for you right away is still a question. Assuming you rebuilt your project after upgrading the package, the 'bin\Roslyn' folder should have been updated then before you saw the runtime error. Which is why your manual removal of the directory makes me suspect that VS/msbuild couldn't remove the old directory for some reason. (Or didn't try to. Who knows. A detailed log of that build might have helped identify the issue.)

At any rate, I'm glad its working for you now. If you ever run into the issue again and are able capture the verbose build output, I'd be happy to look further.

**Comment by UweKeim** [comment]
@StephenMolloy While the copying is not done by nuget scripts, isn't the _inserting_ of the targets into the CSPROJ done by nuget scripts?

**Comment by StephenMolloy** [comment]
@UweKeim Not exactly. The import is added to the project file by nuget itself. In any case, the file does appear to be added to your project because the 'bin\Roslyn' folder was recreated after you deleted the old one. That's why I suspect that the old folder was causing an issue somehow. Everything else appears to be in place, but for some reason we were willing or able to overwrite the old 'bin\Roslyn' folder until you deleted it manually.
