### ISSUE TITLE
Rosyln .refresh files in in asp.net bin folder not copying over .dll files

### ISSUE THREAD

**Issue by brian-pickens-web** [aspnet/RoslynCodeDomProvider#85]
Hello,

This issue may not belong here. If not please help me find the right place to put it.

I'm working with an ASP.NET website project, and trying to only check-in the .refresh files into source control. The problem is that it doesn't appear that the .refresh files in the /bin/rosyln directory are being invoked to restore the .dll's, and so fresh builds are failing. At this point I feel I'm going to have to check in the whole /rosyln directory including all the .dlls and csc.exe for this to work.

Do you have any alternative advice for me?

![2019-03-01 14_15_59-c__workspaces_tfs-workspaces_portalsite_portalsite_bin_roslyn](https://user-images.githubusercontent.com/3659859/53663917-a7071e80-3c2c-11e9-8d36-7f6f08d18160.png)

**Comment by gregpakes** [comment]
I have the same question

**Comment by StephenMolloy** [comment]
This unfortunately can't be fixed with the way this nuget package is structured. Because our nuget packages carries the roslyn binaries directly rather than via nuget reference, we need to be responsible and put them in a subdirectory rather than directly in 'bin'. However, Visual Studio only looks for .refresh files at the root of the bin directory, and not in any subdirectories. Additionally, nuget does not execute any powershell scripts when doing a restore. And WebSite "projects" are actually project-less, which means we can't rely on msbuild or .targets files for any dirty work either.

To work around this, you could check in the exe/dlls as you mentioned. Or you could have a script in your build environment that does the same thing VS does with .refresh files _after_ nuget has restored packages for the project.

Alternatively, if you could migrate to using a Web Application project instead of a Web Site, this issue should no longer be relevant.

**Comment by StephenMolloy** [comment]
A little further explanation. We need to include the roslyn binaries directly in the Microsoft.CodeDom.Providers.DotNetCompilerPlatform package because using the nuget dependency method was causing problems for visual studio. Apparently installing the compilers package properly also installs various .props and .targets files which mess with performance and features for more than just the web project we install this package for. So we ship roslyn binaries directly with this package and stick them in a subfolder of 'bin' to keep them out of the way at design time.

**Comment by brian-pickens-web** [comment]
Thanks for the great explanation. So it sounds like this is actually something that Visual Studio team should resolve by enabling .refresh files to execute in subdirectories.

We ended up opting to check in the binaries as a work around for our website.
