### ISSUE TITLE
Rosyln files locked during publishing

### ISSUE THREAD

**Issue by f3rchu** [aspnet/RoslynCodeDomProvider#88]
I have roslyn DotNetCompilerPlatfrom v2.0.1 in my WebAPI 2 project from .Net Framework 4.7.2
and sometimes when i publish my project, this error is shown:

>No se puede agregar 'bin/roslyn/System.Collections.Immutable.dll' al sitio web.  No se puede agregar el archivo 'bin\roslyn\System.Collections.Immutable.dll'.  El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.
>No se puede agregar 'bin/roslyn/System.Reflection.Metadata.dll' al sitio web.  No se puede agregar el archivo 'bin\roslyn\System.Reflection.Metadata.dll'.  El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

To solve it and allow me to publish my project, I have to reboot my computer. A few publications works, but when this error appears, I can't publish again until the computer restarts.

Update 18/10/2019: I can solve it installing v2.0.0 and reinstalling again v2.0.1. But is the same than with the reboot, the error eventually appear.

Is there another method to resolve it?

Regards.

**Comment by StephenMolloy** [comment]
The error is coming from the publishing destination, and it indicates that we cannot update some roslyn binaries because they are in use. This is probably because the act of publishing is causing ASP.Net to recompile... but it starts recompiling before you're done publishing.  I would expect this error to be intermittent and not require a reboot of your source PC or re-install of any nuget packages. Those tricks probably work because they allow ASP.net enough time to finish compiling and let the roslyn compiler server timeout and exit.

When building locally, we have a build task that will ensure the roslyn compiler server is not running so we can copy dlls successfully. When publishing to a server, we don't have direct control over the roslyn compiler on your server.

I would suggest as a best practice that you use app_offline.htm as part of your publishing process. We have seen customers in the past get caught up with ASP.Net aggressively compiling new content before the publishing process has finished which can lead to assorted interesting errors. Using app_offline.htm should make your publishing process more consistent.

Feel free to re-open if this doesn't solve your issue.
